### ISSUE TITLE
News content not displayed on the front-end.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Rainbow-Quartz#88]
![image](https://cloud.githubusercontent.com/assets/12791909/9459817/538447fe-4b32-11e5-8a3a-e0cc4be6bca0.png)

**Comment by ermatitan** [comment]
Not Fix. Please see updated screenshot:

![image](https://cloud.githubusercontent.com/assets/12791909/9622347/6a386db2-5164-11e5-93db-fb38e2482c9b.png)

**Comment by Rahul-titan** [comment]
Hi Erma,
Here the news page is a default post page. Since titan has blocked the content editor for default posts page we cannot edit or display the news page content in front end. Thanks.

![news page](https://cloud.githubusercontent.com/assets/13828548/9625730/1387eb2a-510d-11e5-9159-8ea6a550871b.PNG)
